// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_2500_meters_time = "CgkIq5i9j7ACEAIQDQ"; // <GPGSID>
        public const string leaderboard_50000_meters_time = "CgkIq5i9j7ACEAIQEQ"; // <GPGSID>
        public const string leaderboard_25000_meters_time = "CgkIq5i9j7ACEAIQEA"; // <GPGSID>
        public const string achievement_first_1000 = "CgkIq5i9j7ACEAIQBQ"; // <GPGSID>
        public const string achievement_first_2500 = "CgkIq5i9j7ACEAIQBg"; // <GPGSID>
        public const string achievement_first_100000 = "CgkIq5i9j7ACEAIQFA"; // <GPGSID>
        public const string achievement_first_50 = "CgkIq5i9j7ACEAIQAQ"; // <GPGSID>
        public const string leaderboard_100000_meters_time = "CgkIq5i9j7ACEAIQEg"; // <GPGSID>
        public const string achievement_first_500 = "CgkIq5i9j7ACEAIQBA"; // <GPGSID>
        public const string leaderboard_1000_meters_time = "CgkIq5i9j7ACEAIQDA"; // <GPGSID>
        public const string leaderboard_500_meters_time = "CgkIq5i9j7ACEAIQCw"; // <GPGSID>
        public const string achievement_first_100 = "CgkIq5i9j7ACEAIQAg"; // <GPGSID>
        public const string achievement_first_25000 = "CgkIq5i9j7ACEAIQCQ"; // <GPGSID>
        public const string leaderboard_10000_meters_time = "CgkIq5i9j7ACEAIQDw"; // <GPGSID>
        public const string achievement_first_250 = "CgkIq5i9j7ACEAIQAw"; // <GPGSID>
        public const string achievement_first_10000 = "CgkIq5i9j7ACEAIQCA"; // <GPGSID>
        public const string achievement_first_5000 = "CgkIq5i9j7ACEAIQBw"; // <GPGSID>
        public const string leaderboard_250_meters_time = "CgkIq5i9j7ACEAIQCg"; // <GPGSID>
        public const string leaderboard_5000_meters_time = "CgkIq5i9j7ACEAIQDg"; // <GPGSID>
        public const string achievement_first_50000 = "CgkIq5i9j7ACEAIQEw"; // <GPGSID>

}

